package com.example.masteringlayoutandtamingthewidgettree51placingwidgetsoneafteranother_proportionallayoutwithflexiblewidgets

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
